main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from main.views import (WorldBorderCreateView, WorldBorderDetailJsonView, WorldBorderDetailView, WorldBorderListView,
                        WorldBorderUpdateView, WorldBorderListJsonView)

app_name = "main"

urlpatterns = [
    path('', TemplateView.as_view(template_name='main/index.html'), name='index'),

    path('geo/', TemplateView.as_view(template_name='main/geo.html'), name='geo'),

    path('borders/create/', WorldBorderCreateView.as_view(), name='worldborder_create'),
    path('borders/list/', WorldBorderListView.as_view(), name='worldborder_list'),

    path('borders/update/<str:worldborder_slug>/', WorldBorderUpdateView.as_view(), name='worldborder_update'),

    path('borders/json/', WorldBorderListJsonView.as_view(), name='worldborder_list_json'),
    path('borders/json/<str:worldborder_slug>/', WorldBorderDetailJsonView.as_view(), name='worldborder_detail_json'),

    path('borders/<str:worldborder_slug>/', WorldBorderDetailView.as_view(), name='worldborder_detail'),
]

main/models.py
from django.contrib.gis.db import models
from django.utils.text import slugify


class WorldBorder(models.Model):
    # Regular Django fields corresponding to the attributes in the
    # world borders shapefile.
    name = models.CharField(max_length=50)
    area = models.IntegerField()
    pop2005 = models.IntegerField('Population 2005')
    fips = models.CharField('FIPS Code', max_length=2)
    iso2 = models.CharField('2 Digit ISO', max_length=2)
    iso3 = models.CharField('3 Digit ISO', max_length=3)
    un = models.IntegerField('United Nations Code')
    region = models.IntegerField('Region Code')
    subregion = models.IntegerField('Sub-Region Code')
    lon = models.FloatField()
    lat = models.FloatField()

    # GeoDjango-specific: a geometry field (MultiPolygonField)
    mpoly = models.MultiPolygonField()

    worldborder_slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        self.worldborder_slug = slugify(self.name)
        super(WorldBorder, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Address(models.Model):
    address = models.CharField(max_length=80)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=80)
    postal_code = models.CharField(max_length=20)

    # def __str__(self):
    #     return ', '.join([self.address, self.postal_code, self.city, self.country])


class Venue(models.Model):
    name = models.CharField(max_length=80, unique=True)

    address = models.OneToOneField(
        Address,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    lat = models.FloatField()
    lon = models.FloatField()

    area_polygon = models.MultiPolygonField(blank=True)

    def __str__(self):
        return self.name


class EventSeries(models.Model):
    slug = models.SlugField(unique=True, max_length=255)

    name: models.CharField(max_length=100, unique=True)
    start_date = models.DateField
    end_date = models.DateField

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(EventSeries, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Round(models.Model):
    slug = models.SlugField(unique=True, max_length=255)

    name: models.CharField(max_length=100, unique=True)
    series = models.ForeignKey(EventSeries, on_delete=models.CASCADE, related_name='rounds')


class Event(models.Model):
    slug = models.SlugField(unique=True, max_length=255)

    name = models.CharField(max_length=80)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()

    # just for testing what this looks like in forms
    date_time = models.DateTimeField()

    series = models.ForeignKey(EventSeries, on_delete=models.CASCADE, related_name='events')
    venue = models.ForeignKey(Venue, on_delete=models.SET_NULL, null=True, related_name='events')
    round = models.ForeignKey(Round, on_delete=models.SET_NULL, null=True, related_name='events')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return self.venue.name + ": " + self.name


class Participant(models.Model):
    slug = models.SlugField(unique=True, max_length=255)

    name = models.CharField(max_length=255)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Participant, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

main/forms.py
from django.contrib.gis import forms as geoforms
from leaflet.forms.widgets import LeafletWidget

from main.models import WorldBorder


class WorldBorderCreateForm(geoforms.ModelForm):

    class Meta:
        model = WorldBorder
        exclude = ['worldborder_slug']
        widgets = {
            'mpoly': LeafletWidget()
        }

main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from djgeojson.views import GeoJSONLayerView

from main.forms import WorldBorderCreateForm
from main.models import WorldBorder


@login_required
def get_user_profile(request, username):
    user = User.objects.get(username=username)
    return render(request, 'main/profile.html', {"user": user})


@method_decorator(login_required, name='dispatch')
class WorldBorderCreateView(CreateView):
    form_class = WorldBorderCreateForm
    template_name = 'main/worldborder_create.html'
    success_url = reverse_lazy('main:worldborder_list')


@method_decorator(login_required, name='dispatch')
class WorldBorderUpdateView(UpdateView):
    form_class = WorldBorderCreateForm
    template_name = 'main/worldborder_update.html'
    success_url = reverse_lazy('main:worldborder_list')
    context_object_name = 'world_border'
    slug_field = 'worldborder_slug'
    slug_url_kwarg = 'worldborder_slug'

    def get_queryset(self):
        b = WorldBorder.objects.get(worldborder_slug=self.kwargs['worldborder_slug'])
        return WorldBorder.objects.filter(name=b.name)


@method_decorator(cache_page(15*60), name='dispatch')
class WorldBorderListView(ListView):
    model = WorldBorder
    context_object_name = 'world_borders'
    paginate_by = 15
    ordering = 'name'


@method_decorator(cache_page(15*60), name='dispatch')
class WorldBorderListJsonView(GeoJSONLayerView):
    model = WorldBorder
    context_object_name = 'world_borders'
    ordering = 'name'
    geometry_field = 'mpoly'


class WorldBorderDetailJsonView(WorldBorderListJsonView):
    slug_field = 'worldborder_slug'
    slug_url_kwarg = 'worldborder_slug'

    def get_queryset(self):
        world_border = WorldBorder.objects.get(worldborder_slug=self.kwargs['worldborder_slug'])
        return WorldBorder.objects.filter(name=world_border)


class WorldBorderDetailView(DetailView):
    model = WorldBorder
    context_object_name = 'world_border'
    slug_field = 'worldborder_slug'
    slug_url_kwarg = 'worldborder_slug'

    def get_queryset(self):
        b = WorldBorder.objects.get(worldborder_slug=self.kwargs['worldborder_slug'])
        return WorldBorder.objects.filter(name=b.name)

main/templates/main/base.html
<!DOCTYPE html>
<head>
  {% load static %}

  <title>Locality Finder</title>

  <link rel="stylesheet" href="{% static 'main/css/materialize.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/material_icons.css' %}">

  <link rel="stylesheet" href="{% static 'main/css/main.css' %}">

  <link rel="shortcut icon" href="{% static 'main/img/locality-finder-pin.png' %}" type="image/png"/>

  {% block custom_includes %}
  {% endblock %}

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

<script type="text/javascript" src="{% static 'main/js/materialize.js' %}"></script>
<script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>

{% include 'main/includes/navbar.html' %}
{% include 'main/includes/sidebar.html' %}

{% include 'main/includes/messages.html' %}

<div class="container content">
  {% block content %}
  {% endblock %}
</div>

<script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>

{% include 'main/includes/footer.html' %}
</body>

main/templates/main/geo.html
{% extends 'main/base.html' %}

{% load static %}
{% load leaflet_tags %}

{% block custom_includes %}
{% leaflet_js %}
{% leaflet_css %}
<link rel="stylesheet" href="{% static 'main/css/leaflet.css' %}">
<script type="text/javascript" src="{% static 'main/js/jquery-3.4.1.min.js' %}"></script>
{% endblock %}

{% block content %}
<h1>Worldborders</h1>

<div class="row">
  {% leaflet_map "main" callback="main_map_init" %}
</div>

<br>

<script type="text/javascript">
    var layer = L.geoJson();

    function main_map_init (map, options) {
        map.addLayer(layer);
    }

    $.getJSON("{% url 'main:worldborder_list_json' %}", function (data) {
        layer.addData(data);
    });

</script>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}
<h1>Test</h1>

<div class="row">
  <p>This is a paragraph!</p>
</div>
<br>
<img class="materialboxed" width="100%" src="{% static 'main/img/flight.jpg' %}">
<br>
{% endblock %}

main/templates/main/logged_out.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}
<h1>Logged out</h1>

<p>
  You have been successfully logged out!
  <br><br>
  You can <a href="{% url 'login' %}">login</a> again or <a href="{% url 'django_registration_register' %}">register</a>
  a new Account.
</p>
{% endblock %}

main/templates/main/login.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}
    <h1>Login</h1>

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}

        <button class="btn" type="submit">login</button>
    </form>

    <br>
    <br>

    If you are not registered yet, go <a href="{% url 'main:register' %}">here</a>
{% endblock %}

main/templates/main/profile.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}
<h1>{{ user.username }}</h1>

<div class="row">
  Yes, this is you!
  {{ user }}
</div>
{% endblock %}

main/templates/main/register.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}
<h1>Registration</h1>

<form method="POST">
  {% csrf_token %}
  {{form.as_p}}

  <button class="btn" type="submit">register</button>
</form>

<br>
<br>

If you are already registered, login <a href="{% url 'login' %}">here</a>
{% endblock %}

main/templates/main/worldborder_create.html
{% extends 'main/base.html' %}

{% load static %}
{% load leaflet_tags %}

{% block custom_includes %}

{% leaflet_js plugins="forms" %}
{% leaflet_css plugins="forms" %}

{% endblock %}

{% block content %}
<h1>Create a new Border</h1>

<form method="POST">
  {{ form }}

  {% csrf_token %}
  <button class="btn" type="submit" id="create_border_submit_btn">save</button>
</form>

<br>
{% endblock %}

main/templates/main/worldborder_detail.html
{% extends 'main/base.html' %}

{% load static %}
{% load leaflet_tags %}

{% block custom_includes %}

{% leaflet_js %}
{% leaflet_css %}
<link rel="stylesheet" href="{% static 'main/css/leaflet.css' %}">
<script type="text/javascript" src="{% static 'main/js/jquery-3.4.1.min.js' %}"></script>

{% endblock %}

{% block content %}
<h1>World Border</h1>

<div class="row">
  {% leaflet_map "main" callback="main_map_init" %}
</div>

<br>

<script type="text/javascript">
    var layer = L.geoJson();

    function main_map_init (map, options) {
        map.addLayer(layer);
    }

    $.getJSON("{% url 'main:worldborder_detail_json' worldborder_slug=world_border.worldborder_slug %}", function (data) {
        layer.addData(data);
    });
</script>
{% endblock %}

main/templates/main/worldborder_detail_json.html
{% load geojson_tags %}

{{ world_border.mpoly|geojsonfeature|safe }}

main/templates/main/worldborder_list.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}
<h1>Borders</h1>

<br>

<ul class="collection">
  {% for border in world_borders %}
  <li class="collection-item">
    <a href="{% url 'main:worldborder_detail' worldborder_slug=border.worldborder_slug %}"
       class="teal-text text-darken-2">
      <i class="material-icons small" style="color:#26a69a">place</i>
      {{ border }}
    </a>
    <a class="secondary-content" href="{% url 'main:worldborder_update' worldborder_slug=border.worldborder_slug %}"><i
      class="material-icons right">edit</i></a>
  </li>
  {% endfor %}
</ul>

{% if is_paginated %}
<ul class="pagination">
  <li class="waves-effect"><a href="?page=1"><i class="material-icons">subdirectory_arrow_left</i></a></li>
  {% if page_obj.has_previous %}
  <li class="waves-effect"><a href="?page={{ page_obj.previous_page_number }}"><i
    class="material-icons">chevron_left</i></a></li>
  {% else %}
  <li class="disabled"><i class="material-icons">chevron_left</i></li>
  {% endif %}
  {% for i in paginator.page_range %}
  {% if page_obj.number == i %}
  <li class="active"><a href="">{{ i }}</a></li>
  {% else %}
  <li class="waves-effect"><a href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
  <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}"><i
    class="material-icons">chevron_right</i></a></li>
  {% else %}
  <li class="disabled"><i class="material-icons">chevron_right</i></li>
  {% endif %}
  <li class="waves-effect"><a href="?page={{ paginator.num_pages }}"><i
    class="material-icons">subdirectory_arrow_right</i></a></li>
</ul>
{% endif %}

{% endblock %}

main/templates/main/worldborder_update.html
{% extends 'main/base.html' %}

{% load static %}
{% load leaflet_tags %}

{% block custom_includes %}

{% leaflet_js plugins="forms" %}
{% leaflet_css plugins="forms" %}

{% endblock %}

{% block content %}
<h1>Create a new Border</h1>

<form method="POST">
  {{ form }}

  {% csrf_token %}

  <br>

  <button class="btn center-align" type="submit" id="create_border_submit_btn">save<i
    class="material-icons right">send</i></button>
</form>

<br>

{% endblock %}