main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from main.views import (WorldBorderCreateView, WorldBorderDetailJsonView, WorldBorderDetailView, WorldBorderListView,
                        WorldBorderUpdateView, WorldBorderListJsonView)

app_name = "main"

urlpatterns = [
    path('', TemplateView.as_view(template_name='main/index.html'), name='index'),

    path('geo/', TemplateView.as_view(template_name='main/geo.html'), name='geo'),

    path('borders/create/', WorldBorderCreateView.as_view(), name='worldborder_create'),
    path('borders/list/', WorldBorderListView.as_view(), name='worldborder_list'),

    path('borders/update/<str:worldborder_slug>/', WorldBorderUpdateView.as_view(), name='worldborder_update'),

    path('borders/json/', WorldBorderListJsonView.as_view(), name='worldborder_list_json'),
    path('borders/json/<str:worldborder_slug>/', WorldBorderDetailJsonView.as_view(), name='worldborder_detail_json'),

    path('borders/<str:worldborder_slug>/', WorldBorderDetailView.as_view(), name='worldborder_detail'),
]

main/models.py
from django.contrib.gis.db import models
from django.utils.text import slugify


class WorldBorder(models.Model):
    # Regular Django fields corresponding to the attributes in the
    # world borders shapefile.
    name = models.CharField(max_length=50)
    area = models.IntegerField()
    pop2005 = models.IntegerField('Population 2005')
    fips = models.CharField('FIPS Code', max_length=2)
    iso2 = models.CharField('2 Digit ISO', max_length=2)
    iso3 = models.CharField('3 Digit ISO', max_length=3)
    un = models.IntegerField('United Nations Code')
    region = models.IntegerField('Region Code')
    subregion = models.IntegerField('Sub-Region Code')
    lon = models.FloatField()
    lat = models.FloatField()

    # GeoDjango-specific: a geometry field (MultiPolygonField)
    mpoly = models.MultiPolygonField()

    worldborder_slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        self.worldborder_slug = slugify(self.name)
        super(WorldBorder, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Address(models.Model):
    address = models.CharField(max_length=80)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=80)
    postal_code = models.CharField(max_length=20)

    # def __str__(self):
    #     return ', '.join([self.address, self.postal_code, self.city, self.country])


class Venue(models.Model):
    name = models.CharField(max_length=80, unique=True)

    address = models.OneToOneField(
        Address,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    lat = models.FloatField()
    lon = models.FloatField()

    area_polygon = models.MultiPolygonField(blank=True)

    def __str__(self):
        return self.name


class EventSeries(models.Model):
    slug = models.SlugField(unique=True, max_length=255)

    name: models.CharField(max_length=100, unique=True)
    start_date = models.DateField
    end_date = models.DateField

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(EventSeries, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Round(models.Model):
    slug = models.SlugField(unique=True, max_length=255)

    name: models.CharField(max_length=100, unique=True)
    series = models.ForeignKey(EventSeries, on_delete=models.CASCADE, related_name='rounds')


class Event(models.Model):
    slug = models.SlugField(unique=True, max_length=255)

    name = models.CharField(max_length=80)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()

    # just for testing what this looks like in forms
    date_time = models.DateTimeField()

    series = models.ForeignKey(EventSeries, on_delete=models.CASCADE, related_name='events')
    venue = models.ForeignKey(Venue, on_delete=models.SET_NULL, null=True, related_name='events')
    round = models.ForeignKey(Round, on_delete=models.SET_NULL, null=True, related_name='events')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return self.venue.name + ": " + self.name


class Participant(models.Model):
    slug = models.SlugField(unique=True, max_length=255)

    name = models.CharField(max_length=255)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Participant, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

main/forms.py
from django.contrib.gis import forms as geoforms
from leaflet.forms.widgets import LeafletWidget

from main.models import WorldBorder


class WorldBorderCreateForm(geoforms.ModelForm):

    class Meta:
        model = WorldBorder
        exclude = ['worldborder_slug']
        widgets = {
            'mpoly': LeafletWidget()
        }

main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from djgeojson.views import GeoJSONLayerView

from main.forms import WorldBorderCreateForm
from main.models import WorldBorder


@login_required
def get_user_profile(request, username):
    user = User.objects.get(username=username)
    return render(request, 'main/profile.html', {"user": user})


@method_decorator(login_required, name='dispatch')
class WorldBorderCreateView(CreateView):
    form_class = WorldBorderCreateForm
    template_name = 'main/worldborder_create.html'
    success_url = reverse_lazy('main:worldborder_list')


@method_decorator(login_required, name='dispatch')
class WorldBorderUpdateView(UpdateView):
    form_class = WorldBorderCreateForm
    template_name = 'main/worldborder_update.html'
    success_url = reverse_lazy('main:worldborder_list')
    context_object_name = 'world_border'
    slug_field = 'worldborder_slug'
    slug_url_kwarg = 'worldborder_slug'

    def get_queryset(self):
        b = WorldBorder.objects.get(worldborder_slug=self.kwargs['worldborder_slug'])
        return WorldBorder.objects.filter(name=b.name)


@method_decorator(cache_page(15*60), name='dispatch')
class WorldBorderListView(ListView):
    model = WorldBorder
    context_object_name = 'world_borders'
    paginate_by = 15
    ordering = 'name'


@method_decorator(cache_page(15*60), name='dispatch')
class WorldBorderListJsonView(GeoJSONLayerView):
    model = WorldBorder
    context_object_name = 'world_borders'
    ordering = 'name'
    geometry_field = 'mpoly'


class WorldBorderDetailJsonView(WorldBorderListJsonView):
    slug_field = 'worldborder_slug'
    slug_url_kwarg = 'worldborder_slug'

    def get_queryset(self):
        world_border = WorldBorder.objects.get(worldborder_slug=self.kwargs['worldborder_slug'])
        return WorldBorder.objects.filter(name=world_border)


class WorldBorderDetailView(DetailView):
    model = WorldBorder
    context_object_name = 'world_border'
    slug_field = 'worldborder_slug'
    slug_url_kwarg = 'worldborder_slug'

    def get_queryset(self):
        b = WorldBorder.objects.get(worldborder_slug=self.kwargs['worldborder_slug'])
        return WorldBorder.objects.filter(name=b.name)

main/templates/main/includes/footer.html
{% load cache %}
{% cache 500 footer %}
<footer class="page-footer teal darken-2">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content Headline</h5>
        <p class="grey-text text-lighten-4">Footer content goes here.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2019 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>
{% endcache %}

main/templates/main/includes/messages.html
{% if messages %}
{% for message in messages %}
{% if message.tags == 'success'%}
<script>M.toast({html: "{{message}}", classes: 'green', displayLength:2000});</script>
{% elif message.tags == 'info'%}
<script>M.toast({html: "{{message}}", classes: 'blue', displayLength:2000});</script>
{% elif message.tags == 'warning'%}
<script>M.toast({html: "{{message}}", classes: 'orange', displayLength:10000});</script>
{% elif message.tags == 'error'%}
<script>M.toast({html: "{{message}}", classes: 'red', displayLength:10000});</script>
{% endif %}
{% endfor %}
{% endif %}

main/templates/main/includes/navbar.html
{% load cache %}
{% cache 500 navbar request.user.username %}
<nav>
  <div class="nav-wrapper teal">
    <a href="{% url 'main:index' %}" class="brand-logo"><i class="material-icons" style="margin-left:15px">home</i></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">

      <li>
        <ul id="map-dropdown" class="dropdown-content">
          <li><a href="{% url 'main:worldborder_list' %}"><i class="large material-icons">view_list</i>List</a></a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'main:worldborder_create' %}"><i class="large material-icons">add_circle</i>Add</a></li>
          {% endif %}
          <li><a href="{% url 'main:geo' %}"><i class="large material-icons">landscape</i>Show all</a></li>
        </ul>
        <a class="btn dropdown-trigger" href="#!" data-target="map-dropdown">World Borders<i
          class="material-icons right">arrow_drop_down</i></a>
      </li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'profile' username=user.username %}">{{user.username|title}}</a></li>
      <li><a href="{% url 'logout' %}">logout</a></li>
      {% else %}
      <li><a href="{% url 'login' %}">login</a></li>
      <li><a href="{% url 'django_registration_register' %}">register</a></li>
      {% endif %}
      <li><a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i
        class="material-icons">menu</i></a></li>
    </ul>
  </div>
</nav>
{% endcache %}

main/templates/main/includes/sidebar.html
{% load cache %}
{% cache 500 sidebar request.user.username %}
<ul id="slide-out" class="sidenav teal darken-3">
  <li><a class="waves-effect" href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
  <li><a class="waves-effect" href="#!">Second Link</a></li>
  <li>
    <div class="divider"></div>
  </li>
  <li><a class="subheader">Subheader</a></li>
  <li><a class="waves-effect" href="#!">Third Link</a></li>
</ul>
{% endcache %}